apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-daniel-jantrambun-net
  namespace: vaultwarden
spec:
  dnsNames:
  - vault.daniel-jantrambun.net
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: vault-staging-tls
